satorijs/satori

- adapters/telegram/src/sender.ts
> fix(telegram): Use URL to parse file uri, fix #7

- adapters/telegram/src/bot.ts
这个 bug 之前居然没有人发现过吗（
TODO 的内容之后另外提交一个 pr
> fix(telegram): fix parsing logic

- adapters/telegram/src/polling.ts
> fix(telegram): pollingTimeout `socket hang up` error, fix #67

- adapters/telegram/package.json
- adapters/telegram/src/bot.ts
- adapters/telegram/src/message.ts
- packages/axios/src/index.ts
移除了与 node 耦合的部分以获得在浏览器加载的能力。
关于文件上传的部分不太确定写的对不对。
> feat(telegram): improve browser compatibility

- adapters/discord/src/bot.ts
https://discord.com/developers/docs/reference#user-agent
> feat(discord): add user agent

- packages/axios/src/index.ts
> fix: filename does not contain an extension

- adapters/feishu/src/bot.ts
> feat(feishu): refresh token every 1 hour

- adapters/kook/src/index.ts
- adapters/kook/src/utils.ts
> feat(kook): support event `message_btn_click`

- adapters/lark/src/http.ts
> fix(lark): not compare verification token if undefined

- adapters/onebot/src/types.ts
- adapters/onebot/src/utils.ts
Support group file upload and offline file recived.
This pull request may have some issues. I would appreciate any feedback to help improve it. 🙏
close #109
> feat(onebot): support file message

- adapters/mail/src/bot.ts
> fix(mail): add reconnect status, fix #115

- adapters/qqguild/src/bot.ts
> fix(qqguild): fix image was parsed twice

- adapters/telegram/package.json
- adapters/telegram/src/bot.ts
> fix(telegram): telegram sticky file mime type

- adapters/lark/src/bot.ts
- adapters/lark/src/types/message/index.ts
- adapters/lark/src/utils.ts
> feat(lark): support getMessage and getMessageList

- adapters/lark/src/bot.ts
- adapters/lark/src/types/index.ts
- adapters/lark/src/types/user.ts
- adapters/lark/src/utils.ts
> feat(lark): support getUser

- adapters/lark/src/bot.ts
- adapters/lark/src/types/guild.ts
- adapters/lark/src/utils.ts
> feat(lark): add getGuild / getChannel / getGuildMemberList etc

- adapters/qq/src/bot/index.ts
> fix(qq): fix sandbox for group bot

- adapters/qq/src/utils.ts
> 删除了按钮响应失败的报错

- adapters/satori/src/ws.ts
> fix(satori): missing `status`, fix koishijs/koishi#1367, fix #241

- adapters/qq/src/message.ts
Credit to https://github.com/idanran/koishi-plugin-adapter-red/blob/631fde743cba80759bee9d3fbaeda482633818ad/src/message.ts#L138
> feat(qq): send non-silk audio

- adapters/dingtalk/src/http.ts
- adapters/dingtalk/src/internal.ts
- adapters/dingtalk/src/ws.ts
> fix(dingtalk): internal api result parsing

- adapters/telegram/package.json
- adapters/telegram/src/bot.ts
- adapters/telegram/src/message.ts
- adapters/telegram/src/utils.ts
- packages/element/src/index.ts
This PR involves the following changes:
- Support media group when sending messages.
- Support media group when receiving messages.
- Rewrite the parser of rich text to support bold, italic, ...
> feat(telegram): support media group, improve message parsing

- adapters/telegram/src/message.ts
测试内容：`<quote>test</quote>wwwww`
效果：
> feat(telegram): support blockquote

- adapters/qq/src/utils.ts
> feat(qq): interaction/button event add button data

- adapters/qq/src/utils.ts
Also fixes group message parsing.
> feat(qq): support get group user avatar

- adapters/qq/src/message.ts
已在本地测试通过
测试用代码：
```ts
export function apply(ctx: Context) {
ctx
.command('发')
.action(() =>
h('audio', {
src: pathToFileURL('D:/a.mp3').toString(),
}),
)
}
```
> feat(qq): support ntsilk service

- adapters/qq/src/bot/index.ts
> fix(qq): initialize `bot.user`
