satorijs/satori

adapters/telegram/src/index.ts
adapters/telegram/src/utils.ts

Support for telegram internal events:
- telegram/inline-query
- telegram/chosen-inline-result
- telegram/callback-query
- telegram/shipping-query
- telegram/pre-checkout-query
- telegram/poll
- telegram/poll-answer
- telegram/chat-member

feat(telegram): emit telegram internal events

---

adapters/kook/src/bot.ts

No file name will cause the server to return error code 40000. Add a file name to avoid the error.

fix(kook): failed to create asset

---

adapters/telegram/src/bot.ts

adapter 接收消息时不应该将 `quote` 加入 `segments` 中。
改用 `adaptMessage` 的原因是，原本这里只做了很简单的消息处理，并没有处理图片等更复杂的内容。
另外这里的 `as Session`，是否将 `adaptMessage` 的参数 `session` 的类型更改为 `Message` 更好呢，不过这样的话需要修改这个函数中大量出现的 `session`，不知道 @shigma 的意见如何。

fix(telegram): adapt reply message

---

packages/core/src/session.ts

在`Session`中加入了一个`fid`（full id）。类似于`cid`、`gid`以及`sid`。
作用是创建一个与平台，群组，用户都相关的标识符。可以做到不同平台，可以做到同一个平台，同一个用户在不同群组中也有不同的id。
对一些服务（比如[chatgpt-bot](https://github.com/koishijs/chatgpt-bot)的上下文）很有用。
```ts
get fid() {
return `${this.platform}:${this.channelId}:${this.userId}`
}
```

feat: add `session.fid` as user context identifier

---

adapters/kook/src/bot.ts

getGuildMemberList() didn't passing `guild_id`
fix koishijs/koishi-plugin-marry#1

fix(kook): getGuildMemberList didn't passing `guild_id`

---

adapters/kook/src/utils.ts

body 中的 user_info 字段需要传过来，将 body 放入 extra 中

fix(kook): added `extra` field for `kook/message-btn-click`

---

adapters/kook/src/types.ts

feat(kook): fix Kook types #121

---

packages/satori/src/router.ts

用于 `wecom`, `wechatofficial` ~等~平台的 webhook 传入

fix(core): support xml body

---

adapters/matrix/src/bot.ts
adapters/matrix/src/utils.ts

fix(matrix): same guild and channel, fix koishijs/koishi#1158

---

adapters/discord/src/bot.ts
adapters/discord/src/types/command.ts
adapters/discord/src/utils.ts

- 修复了私聊无法使用 slash commands
- 修复了指令重复更新的问题

fix(discord): slash commands

---

adapters/dingtalk/src/message.ts
adapters/discord/src/message.ts
adapters/kook/src/message.ts
adapters/lark/src/message.ts
adapters/line/src/message.ts
adapters/mail/src/message.ts
adapters/matrix/src/message.ts
adapters/onebot/src/bot/message.ts
adapters/qqguild/src/message.ts
adapters/slack/src/message.ts
adapters/telegram/src/message.ts
adapters/wechat-official/src/message.ts
adapters/wecom/src/message.ts
adapters/whatsapp/src/message.ts

- All adapter
- lark
- line
- qqguild
Check for previous `\n`. If no, then append `\n`.
No check for previous `\n`, append `\n` immediately.
- dingtalk
- kook
- matrix
- slack
- telegram
- wechat-offical
- wecom
- whatsapp
close koishijs/koishi#1185

feat: add `br` and `p` element support and fix `p` behavior

---

adapters/qq/src/message.ts

发送消息的行为永远在频道发生，因此请永远使用 channelId 而非 guildId。

fix(qq): fix send group msg using `bot.sendMessage()`

---

adapters/qq/src/message.ts

为 QQ 适配器引入 `passive` 元素，属于元信息元素，定义如下：
| 属性 | 类型 | 范围 | 描述 |
| --- | --- | --- | --- |
| id | string | 发 | 关联的消息 |
| seq | number? | 发 | 消息的序号，同 id 同 seq 的被动消息只会被发送一次 |

feat(qq): support `passive` element

---

adapters/lark/src/bot.ts
adapters/lark/src/types/message/index.ts
adapters/lark/src/types/user.ts

This commit add APIs for "forwarding messages" and "merging and forwarding messages", also changing the original `getUserInfo` function to the consist one `getContactUser`
Fix #207

feat(lark): add more api, correct function name

---

adapters/discord/src/message.ts
adapters/kook/src/message.ts
adapters/telegram/src/message.ts
adapters/zulip/src/message.ts
packages/core/src/message.ts

implements and supersedes #196.
Affected adapters:
- discord
- kook
- telegram
- zulip
cc @ilharp @XxLittleCxX

feat(satori): drop legacy encoder.guildId

---

packages/axios/src/index.ts

此 PR 旨在使 `Quester.file` 返回的 filename 基于最终访问的 URL

feat(axios): handle http redirect

---

adapters/discord/src/utils.ts

* I think the `required` argument of options in `Universal.Command` denotes whether a *value* should be present,
* however, the `required` argument in Discord denotes whether *this option* should be present.

fix(discord): confuse of `required` argument

---

adapters/telegram/src/bot.ts

I run [telegram-bot-api](https://github.com/tdlib/telegram-bot-api) with `--local` argument and enable `files.local` config in Koishi. When I use any API that returns a file (e.g. `getUser` will return user's avatar), I will get a `TypeError: Invalid URL` error like this.
```log
1000|2|2024-05-29 13:20:18 [W] telegram get file error TypeError: Invalid URL: /stor/opt/bot/telegram/***/profile_photos/file_52.jpg at Proxy.resolveURL (/home/su226/.koishi/data/instances/default/node_modules/@cordisjs/plugin-http/lib/index.cjs:250:13) at [cordis.invoke] (/home/su226/.koishi/data/instances/default/node_modules/@cordisjs/plugin-http/lib/index.cjs:278:22) at applyTraceable (/home/su226/.koishi/data/instances/default/node_modules/@cordisjs/core/lib/index.cjs:263:) at Object.apply …
```

fix(telegram): Invalid URL when enabled files.local

---

adapters/discord/src/types/user.ts
adapters/discord/src/utils.ts

This PR add missing global_name field definition of Discord User and fill it into Universal User's nick field.

feat(discord): add missing global_name field

---

adapters/discord/src/utils.ts

This PR implement adapting sticker items into following element
```tsx
<sticker id="id" format_type="format_type" name="name">
</sticker>
```

feat(discord): support sticker elements

---

adapters/qq/src/message.ts

fix(qq): fix audio encoding

---

adapters/qq/src/internal/group.ts
adapters/qq/src/message.ts

Add support for the new data format returned by the QQ platform for proactive message audits.

fix(qq): integrate new audit structure in sending message

---

adapters/telegram/src/message.ts

- adapting code block into following element
```<code-block lang=python>import numpy as np\n\nb = 1</code-block>```.
- enhance code element support, now both `<code content="foo"/>` and `<code>foo</code>` are accepted.
- Considering compatibility, `content` attribute takes higher priority as `<code content="foo">bar</code>` will display `foo` in current implementation.
```ts
session.send(
`<code content="foo" /> | <code>bar</code> | <code content="baz">qux</code>
<br />
<code content="&&gt;=&lt;&" /> | <code>&&gt;=&lt;&</code>
<br />
<code-block>import os, sys\nimport numpy as np\n\na = &quot;&amp;&gt;=&lt;&amp;&quot;</code-block>
<br />
Display as plain text:
<code-block lang="txt">import os, sys\nimport numpy as np\n\na = "&&gt;=&lt;&"</code-block>
To display code block in telegram: …
```

feat(telegram): support code block and enhance code support

---

adapters/telegram/src/utils.ts

When the message is sent by user using inline_query feature with attached button, this callback_query will not include any chat object.

adapter-telegram: only detect chat type if chat object exists
